# Generated by Django 4.2.7 on 2023-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarization_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='new_inventory_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
