# Generated by Django 4.2.7 on 2023-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarization_app', '0003_rename_new_inventory_number_inventoryitem_previous_year_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number_1', models.CharField(max_length=255, verbose_name='Инвентарный номер (1)')),
                ('inventory_number_2', models.CharField(max_length=255, verbose_name='Инвентарный номер (2)')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('location_2022', models.CharField(max_length=255, verbose_name='Расположение в 2022 году')),
                ('location_2023', models.CharField(max_length=255, verbose_name='Расположение в 2023 году')),
                ('acquisition_date', models.DateField(verbose_name='Дата принятия')),
            ],
        ),
    ]
